language: ruby
cache:
- bundler
rvm:
- 2.5.3
- jruby
env:
- DB=postgresql
script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- psql -c 'create database my_app_test' -U postgres
before_install:
- gem update --system
- gem install bundler
deploy:
  provider: heroku
  api_key:
    secure: nRQfh/Tsel4hwH3oiaJ4ujjLuJdkFu4/im2Ty2SPdUtG4dJyqiE4RM5BQkfEgDiKwYrId773V87YLpRIDU+w4rv+eCGCXHB/LzSsae5K+30ZudUHPqv3D/818n9p28vv8s/yd1vySRGDlGKjeyN4b4co75UDVzcsmLAIwo1Al4NNifhIQCXNqaNFiWaLawqr7+y0fUhiyHguhO0Yxqry5cq6ndBwy7gu9vd9PLceWUxYqfWbK+mMEpenWit6x0sRKCtWMbHTuSwctX8/qOfZP3waI8+Vpu0E2bp7OSycm6P1iWNsUiU8xFx+KeOhKRg/VNLzRvn93Aeslsu94+hxI3P1O5dNWXsrfQx/Bu8S7qmThlNOFdnuITZ5PkRRsxkqCz/2IiBZT4Wjdqt/ifn/RKflaoX/Yl71kxbCxKg04eospJCz24C8Uss46uzFdO7KTzx4qbzg6Lx3E4RfVHv244QpDzls4Dzpm56AhVm9EYbjHyngs5TaIh/Ql+miZ5o+O1z+Lsin0uYk/DgYctWoHXON6TIrTAIM0XOfKu3hKtJxHs/I/m6JB4KwLRybtozudsw7oPQbO1GMSRcfol/Oy6FVtUd+vu1nhUFur0JGFOUiCxg+4Hpmu6w2QkSTjT1GVHpCeObUV7tsjZnH/n2BV3XTN9/BLk1tMRdP0odMXlQ=
  app: jaidbook
  on:
    repo: AsadK47/Jaidbook
