language: ruby
cache:
- bundler
rvm:
- 2.5.3
- jruby
env:
- DB=postgresql
script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- psql -c 'create database my_app_test' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: vzCjGq79syYdRggAZMlrkH4BDMqt+2KIo33GBLX6xmD3hFawQWlv7sn8iizVP64nKSZcRqkFxl1NmXqynWPsg3SU6msv4SlUCrnydXTUsRDH6ofIAyHaC1hhOus53Q5Yo6zM5ANIa96f2c2t4512RsTFHqSHC0BctVqchuF/766ynTSAxPvanbQCVI3NX7bHTdo4RqEL65i0AtE/jwj2yZNGxKkgYcczigkWshxK1thtE6pdNyCJaivjzeCQ7yeMjRooyvrZ1qqBPYBiV+cRmu2gLfp/RKfZdnDaFd8ovXSqxAi2dxpP0GmyXxxmDnAkWJu96iRCxLpRYl9otL13NR1PS08jcIUegoTtVa22obCxSaNDDqJIeDn0E6KkDDazliUsV5fKGEeGj0G+jvYdoWiP7IMrkxT10q6e+P0Nn+Ho2lHkaz6WiwDZYbsWatf0oAJYF4YZXo/J2yzyjna5EACEpsQghKpjOZaevl41++WwyCLkVGWljTpUnTC/LKk2JWXS/SKPzvo2KA8TSMpfZ18yTVdYoQef0i+jFPIxa7U6sJUInoaRJ7XeSZTOoH+gx767q/9OztXx99XzV/siEdDOJV+FiSFOF72rR68HzmQ9/iWBx4cQEfwjw9vCV4bafdRA1XHWMydEvyaYTnEsdipEJdXe2wpjimxVA5F5KXI=
  app: jaidbook
  on:
    repo: AsadK47/Jaidbook
