language: ruby
cache:
- bundler
rvm:
- 2.5.3
env:
- DB=postgresql
script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- psql -c 'create database my_app_test' -U postgres
before_install:
- gem update --system
- gem install bundler
deploy:
  provider: heroku
  api_key:
    secure: giz2sxEEeAW38X7b57DWcexuUTfda/bTSPSpW/Vh7Pluc41jaiJZmXlNEx/VcosLKwL8FBACS5CZBS+KqBZ41JfQLiheXDxZCcmM5znZXXypi6OQ2oqcPD4Jz9JN0jHJv+ig/NrFOi4a6GuEjHB7JMCQpX8q8URVpiEKoth4oEMDU7bLCTicw2p+efFjSvAr7zfG5HrboKMCI8s4O5xcKCgH3uswtuoF9Z+sCQmOi/c8rsrCJqkmN3E8Thz+fEGLCuTbqsXWsP1p1gQ0CxPGv0GVDbPPRyZ1lvisyzxoWfgrHo8a6D6duZUGQbZfDZlEJ7rYHcwE0RqjJervUCyJMfoL1NSKtxMM0jrjOAjhuYp98WNqwlNsVZAooFyI0TZMMgezR380D0pRJ7qGXNrjXx4kPnm0289MJSlMyWPd+St0RvQT7m3k6vUyk+ufpjbM5Oqa/9eUuQ+Tfn1EqiHScb7+C9QnvloxQPR1vfeNNJ71/qbNFr94D4Mlp2JLAjc1Mt+pD8QWVbG3lcEPjlZ4urhfxdyByfXjZ0ChHi89bXxoXCZaKDhxmbswi8CkFWl24UwfFGlXKniHKnMRR3TPzoS0utwf/NubnGBE6MQ+EPvzt/AjRSNnHNsGipU3pLYh17H/SJt/QQhyK0t/kwiLFpVan3vq5tnRF0QXb45vCmg=
  app: jaidbook
  on:
    repo: AsadK47/Jaidbook
